id = "LRFLEW.TenMinuteEnergy"
name = "TenMinuteEnergy"
description = "Drink Stacking Mod"
version = "1.0.1"
homepage = "https://github.com/LRFLEW/WEBFISHING.TenMinEnergy"
author = "LRFLEW"

icon = "icon.png"
readme = "README.md"
changelog = "CHANGELOG.md"

[project]
csharp = "./LRFLEW.TenMinuteEnergy/LRFLEW.TenMinuteEnergy.csproj"

[[dependencies]]
thunderstore_version = "NotNet-GDWeave-2.0.14"
